print('enter a number and then the power to find sum of digits in the respective output')
print(end = '\n')
x = int(input('Enter a number: '))
y = int(input('Enter a power: '))
o = (x**y)
strls = list(str(o))
intlist = list(map(int, strls))
c = sum(intlist)
print(c)
